name: dead-mans-switch
services:
- name: web
  source_dir: /
  github:
    repo: 0xWizzzz/DeadManSwitch
    branch: main
  run_command: npm start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "4173" 